### ISSUE TITLE
请问有java的sdk吗

### ISSUE THREAD

**Issue by WizWild** [vasblock/developer#1]
如上，想接入您们的vas，我看只有通过rpc的方式调用，请问有java相关的sdk或者是样例程序吗，谢谢~

**Comment by vasblock** [comment]
目前暂时没有，抱歉
________________________________
发件人: yyicon <notifications@github.com>
发送时间: 2019年11月18日 18:53
收件人: vasblock/developer <developer@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [vasblock/developer] 请问有java的sdk吗 (#1)


如上，想接入您们的vas，我看只有通过rpc的方式调用，请问有java相关的sdk或者是样例程序吗，谢谢~

―

**Comment by WizWild** [comment]
好的，谢谢
